---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Install key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927

    - name: Install repo MongoDB
      lineinfile:
        path: /etc/apt/sources.list.d/mongodb-org-3.2.list
        line: 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse'
        create: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        update_cache: yes

    - name: Enable MongoDB
      systemd:
        name: mongod
        enabled: yes
