---
- name: Install Ruby
  hosts: all
  become: true
  tasks:
    - name: Install Ruby
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - ruby-full
          - ruby-bundler
          - build-essential
